export const spacing = {
  container: 'container mx-auto py-8 px-4',
  containerTight: 'container mx-auto py-4 px-4',
  containerWide: 'container mx-auto py-12 px-6',
  cardPadding: 'p-6',
  cardPaddingSmall: 'p-4',
  cardPaddingLarge: 'p-8',
  section: 'space-y-6',
  sectionSmall: 'space-y-3',
  sectionLarge: 'space-y-8',
  sectionTight: 'space-y-2',
  sectionLoose: 'space-y-12',
  stack: 'space-y-4',
  stackTight: 'space-y-2',
  stackLoose: 'space-y-6',
  inline: 'gap-4',
  inlineSmall: 'gap-2',
  inlineLarge: 'gap-6',
  inlineTight: 'gap-1',
  inlineLoose: 'gap-8',
} as const

export const typography = {
  h1: 'text-3xl font-bold',
  h2: 'text-2xl font-bold',
  h3: 'text-xl font-semibold',
  h4: 'text-lg font-semibold',
  h5: 'text-base font-semibold',
  body: 'text-base',
  bodySmall: 'text-sm',
  bodyLarge: 'text-lg',
  muted: 'text-sm text-muted-foreground',
  mutedSmall: 'text-xs text-muted-foreground',
  mutedLarge: 'text-base text-muted-foreground',
  link: 'text-primary hover:underline transition-colors',
  linkMuted: 'text-muted-foreground hover:text-foreground transition-colors',
  linkSubtle: 'hover:text-primary transition-colors',
  truncate: 'truncate',
  lineClamp1: 'line-clamp-1',
  lineClamp2: 'line-clamp-2',
  lineClamp3: 'line-clamp-3',
} as const

export const layout = {
  pageGrid: 'grid grid-cols-1 lg:grid-cols-4 gap-8',
  pageMain: 'lg:col-span-3',
  pageSidebar: 'space-y-6',
  flexBetween: 'flex items-center justify-between',
  flexCenter: 'flex items-center justify-center',
  flexStart: 'flex items-center justify-start',
  flexEnd: 'flex items-center justify-end',
  flexCol: 'flex flex-col',
  flexColCenter: 'flex flex-col items-center justify-center',
  flexGap: 'flex items-center gap-2',
  flexGapSmall: 'flex items-center gap-1',
  flexGapLarge: 'flex items-center gap-4',
  grid2: 'grid grid-cols-1 md:grid-cols-2 gap-4',
  grid3: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4',
  grid4: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4',
  hideMobile: 'hidden sm:block',
  hideTablet: 'hidden md:block',
  hideDesktop: 'block md:hidden',
  showMobile: 'block sm:hidden',
} as const

export const interactive = {
  button: 'transition-colors',
  buttonIcon: 'mr-2 h-4 w-4',
  buttonIconOnly: 'h-4 w-4',
  card: 'overflow-hidden',
  cardHover: 'overflow-hidden transition-shadow hover:shadow-md',
  cardClickable: 'overflow-hidden transition-all hover:shadow-md cursor-pointer',
  input: 'w-full',
  inputGroup: 'space-y-2',
  loading: 'animate-pulse',
  spinning: 'animate-spin',
  disabled: 'opacity-50 cursor-not-allowed',
  clickable: 'cursor-pointer',
  transition: 'transition-all duration-200',
  transitionFast: 'transition-all duration-100',
  transitionSlow: 'transition-all duration-300',
} as const

export const sizes = {
  icon: 'h-4 w-4',
  iconSmall: 'h-3 w-3',
  iconLarge: 'h-5 w-5',
  iconXLarge: 'h-6 w-6',
  icon2XLarge: 'h-8 w-8',
  iconWithText: 'mr-2 h-4 w-4',
  iconWithTextSmall: 'mr-1.5 h-3 w-3',
  iconWithTextLarge: 'mr-2 h-5 w-5',
  avatar: 'h-10 w-10',
  avatarSmall: 'h-8 w-8',
  avatarLarge: 'h-12 w-12',
  avatarXLarge: 'h-16 w-16',
  containerNarrow: 'max-w-2xl mx-auto',
  containerMedium: 'max-w-4xl mx-auto',
  containerWide: 'max-w-6xl mx-auto',
  containerFull: 'max-w-7xl mx-auto',
} as const

export const composite = {
  cardContent: 'p-6 space-y-4',
  cardContentSmall: 'p-4 space-y-3',
  cardContentLarge: 'p-8 space-y-6',
  formGroup: 'space-y-2',
  formGroupTight: 'space-y-1',
  formGroupLoose: 'space-y-4',
  listItem: 'py-3 border-b last:border-b-0',
  listItemHover: 'py-3 border-b last:border-b-0 hover:bg-muted/50 transition-colors',
  emptyState: 'py-12 text-center',
  errorState: 'py-12 text-center',
  loadingState: 'py-12 flex items-center justify-center',
} as const
